# Site settings
title: Esequiel Virtuoso
description: Esequiel Virtuoso Professional Profile
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:5000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Esequiel Virtuoso
user_description: I am a developer specialized in Goland data APIs, also an Agile lover (❤ SCRUM). Currently, I am living in Brazil, however, you can email me or leave a message on Linkedin. I will be glad to help you!
user_title: Data Engineer.
email: virtuosoesequiel@gmail.com
twitter_username: lorem_ipsum
github_username:  esequielvirtuoso
gplus_username:  virtuosoesequiel

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
