# Site settings
title: Esequiel Virtuoso
description: Esequiel Virtuoso Professional Profile
favicon:
  source: github-logo.png
  path: /assets/img
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:5000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Esequiel Virtuoso
user_description: I am passionate about coding JavaScript, Node.JS and I am also passionate about building Business Intelligence Applications with QlikView, Power BI, and Pentaho. Currently, I am living in Brazil, however, you can email me or leave a message on Linkedin. I will be glad to help you!
user_title: Software Developer and BI Analyst
email: virtuosoesequiel@gmail.com
twitter_username: lorem_ipsum
github_username:  esequielvirtuoso
gplus_username:  virtuosoesequiel

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
