# Site settings
title: EV
description: Esequiel Virtuoso Professional Profile
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Esequiel Virtuoso
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer and BI Analyst
email: virtuosoesequiel@gmail.com
twitter_username: lorem_ipsum
github_username:  esequielvirtuoso
gplus_username:  virtuosoesequiel

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
